# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e2da9b199a77e2d0c475e2de7937bda6a6a1b0ae6a38865aeb3f9a8366428641ae6392196a7df64ab4f4f84333ed05c758ad0652458e713cf4939b931b7e31

test:
  secret_key_base: 6a0a760cb3946ed78b3ff6aaa75f52a68aef1ea37e6e391fe834e4e53783033e6089ab2846499c282ccfe95986062ee6849c403a1c84b90e1853808e8e3507c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
